version: '2'

services:

    huitparfait-auth:
        environment:
            FACEBOOK_CLIENT_ID: FACEBOOK_CLIENT_ID
            FACEBOOK_CLIENT_SECRET: FACEBOOK_CLIENT_SECRET
            GOOGLE_CLIENT_ID: GOOGLE_CLIENT_ID
            GOOGLE_CLIENT_SECRET: GOOGLE_CLIENT_SECRET
            YAHOO_CLIENT_ID: YAHOO_CLIENT_ID
            YAHOO_CLIENT_SECRET: YAHOO_CLIENT_SECRET

    huitparfait-auth:
        environment:
            NEO4J_URL: http://neo4j:neo@huitparfait-data:7474