version: '2'

services:

    huitparfait-auth:
        environment:
            NODE_ENV: development
            FACEBOOK_CLIENT_ID: TO_POPULATE
            FACEBOOK_CLIENT_SECRET: TO_POPULATE
            GOOGLE_CLIENT_ID: TO_POPULATE
            GOOGLE_CLIENT_SECRET: TO_POPULATE
            YAHOO_CLIENT_ID: TO_POPULATE
            YAHOO_CLIENT_SECRET: TO_POPULATE
